In [ ]:
import fastf1
session = fastf1.get_session(2026, "Dutch Grand Prix", "Qualifying")
session.load()
session.results

core           INFO 	Loading data for Dutch Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '63', '12', '81', '44', '16', '3', '30', '5', '41', '10', '22', '27', '43', '31', '23', '55', '14', '18', '87', '77', '11']

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,1.0,,NaN,0 days 00:01:12.695000,0 days 00:01:11.628000,0 days 00:01:11.163000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:12.924000,0 days 00:01:11.959000,0 days 00:01:11.265000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,3.0,,NaN,0 days 00:01:13.022000,0 days 00:01:11.915000,0 days 00:01:11.296000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,4.0,,NaN,0 days 00:01:12.610000,0 days 00:01:11.641000,0 days 00:01:11.305000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,5.0,,NaN,0 days 00:01:12.673000,0 days 00:01:11.970000,0 days 00:01:11.494000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,6.0,,NaN,0 days 00:01:13.064000,0 days 00:01:11.910000,0 days 00:01:11.558000,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,7.0,,NaN,0 days 00:01:13.290000,0 days 00:01:11.874000,0 days 00:01:11.618000,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Red Bull Racing,4781D7,red_bull,Liam,Lawson,Liam Lawson,...,8.0,,NaN,0 days 00:01:13.392000,0 days 00:01:12.301000,0 days 00:01:11.733000,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,9.0,,NaN,0 days 00:01:13.142000,0 days 00:01:12.433000,0 days 00:01:12.079000,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,10.0,,NaN,0 days 00:01:13.074000,0 days 00:01:12.525000,0 days 00:01:12.185000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,11.0,,NaN,0 days 00:01:13.115000,0 days 00:01:12.616000,NaT,NaT,,NaN,NaN
22,22,Y TSUNODA,TSU,tsunoda,Racing Bulls,6C98FF,rb,Yuki,Tsunoda,Yuki Tsunoda,...,12.0,,NaN,0 days 00:01:13.085000,0 days 00:01:12.627000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,13.0,,NaN,0 days 00:01:13.188000,0 days 00:01:12.797000,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,14.0,,NaN,0 days 00:01:13.322000,0 days 00:01:12.800000,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,15.0,,NaN,0 days 00:01:13.544000,0 days 00:01:13.137000,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,16.0,,NaN,0 days 00:01:13.552000,0 days 00:01:13.182000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,17.0,,NaN,0 days 00:01:13.574000,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,18.0,,NaN,0 days 00:01:13.650000,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,19.0,,NaN,0 days 00:01:13.818000,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,20.0,,NaN,0 days 00:01:13.826000,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,21.0,,NaN,0 days 00:01:14.371000,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,22.0,,NaN,0 days 00:01:14.600000,NaT,NaT,NaT,,NaN,NaN

In [14]:
session.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:18:14.116000,NOR,1,NaT,1.0,1.0,0 days 00:16:47.086000,NaT,NaT,0 days 00:00:29.478000,...,False,McLaren,0 days 00:16:47.086000,2026-08-22 14:03:22.850,1,NaN,False,,False,False
1,0 days 00:19:36.032000,NOR,1,0 days 00:01:21.916000,2.0,1.0,NaT,NaT,0 days 00:00:27.948000,0 days 00:00:28.003000,...,False,McLaren,0 days 00:18:14.116000,2026-08-22 14:04:49.880,1,NaN,False,,False,True
2,0 days 00:20:49.092000,NOR,1,0 days 00:01:13.060000,3.0,1.0,NaT,NaT,0 days 00:00:25.162000,0 days 00:00:25.717000,...,False,McLaren,0 days 00:19:36.032000,2026-08-22 14:06:11.796,1,NaN,False,,False,True
3,0 days 00:22:29.924000,NOR,1,0 days 00:01:40.832000,4.0,1.0,NaT,0 days 00:22:27.411000,0 days 00:00:34.663000,0 days 00:00:31.557000,...,False,McLaren,0 days 00:20:49.092000,2026-08-22 14:07:24.856,1,NaN,False,,False,False
4,0 days 00:28:02.660000,NOR,1,NaT,5.0,2.0,0 days 00:26:34.169000,NaT,NaT,0 days 00:00:28.482000,...,False,McLaren,0 days 00:22:29.924000,2026-08-22 14:09:05.688,1,NaN,False,,False,False

In [15]:
session.laps.pick_teams("Red Bull Racing").sort_values("LapTime").head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
151,0 days 01:09:56.406000,VER,3,0 days 00:01:11.618000,21.0,5.0,NaT,NaT,0 days 00:00:24.533000,0 days 00:00:25.320000,...,True,Red Bull Racing,0 days 01:08:44.788000,2026-08-22 14:55:20.552,1,NaN,False,,False,True
148,0 days 01:04:32.861000,VER,3,0 days 00:01:11.677000,18.0,4.0,NaT,NaT,0 days 00:00:24.543000,0 days 00:00:25.263000,...,True,Red Bull Racing,0 days 01:03:21.184000,2026-08-22 14:49:56.948,1,NaN,False,,False,True
176,0 days 01:10:01.724000,LAW,30,0 days 00:01:11.733000,24.0,6.0,NaT,NaT,0 days 00:00:24.574000,0 days 00:00:25.221000,...,True,Red Bull Racing,0 days 01:08:49.991000,2026-08-22 14:55:25.755,1,NaN,False,,False,True
173,0 days 01:04:44.889000,LAW,30,0 days 00:01:11.811000,21.0,5.0,NaT,NaT,0 days 00:00:24.682000,0 days 00:00:25.234000,...,True,Red Bull Racing,0 days 01:03:33.078000,2026-08-22 14:50:08.842,1,NaN,False,,False,True
144,0 days 00:51:47.538000,VER,3,0 days 00:01:11.874000,14.0,3.0,NaT,NaT,0 days 00:00:24.769000,0 days 00:00:25.304000,...,True,Red Bull Racing,0 days 00:50:35.664000,2026-08-22 14:37:11.428,1,NaN,False,,False,True

In [18]:
session.laps[session.laps["Driver"] == "VER"].get_car_data().head()

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2026-08-22 14:01:15.572,3590.0,14.0,1,0.0,False,0,car,0 days 00:00:00.226000,0 days 00:14:39.808000
1,2026-08-22 14:01:16.693,3288.0,25.0,1,0.0,False,0,car,0 days 00:00:01.347000,0 days 00:14:40.929000
2,2026-08-22 14:01:17.013,3289.0,28.0,1,0.0,False,0,car,0 days 00:00:01.667000,0 days 00:14:41.249000
3,2026-08-22 14:01:17.213,3554.0,31.0,1,0.0,False,0,car,0 days 00:00:01.867000,0 days 00:14:41.449000
4,2026-08-22 14:01:17.493,3672.0,33.0,1,0.0,False,0,car,0 days 00:00:02.147000,0 days 00:14:41.729000

In [17]:
session.weather_data.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:22.921000,18.2,56.3,1020.6,False,34.3,77,1.9
1,0 days 00:01:23.132000,18.3,55.7,1020.6,False,34.5,50,1.3
2,0 days 00:02:23.187000,18.3,55.4,1020.6,True,33.3,63,3.1
3,0 days 00:03:22.929000,18.4,56.4,1020.6,False,32.0,24,2.7
4,0 days 00:04:23.803000,18.4,56.0,1020.7,False,31.9,76,2.5