In [1]:
import pandas as pd

LAPS_PATH = "../data/raw/laps/season=2024/round=1/session=R/data.parquet"

df = pd.read_parquet(LAPS_PATH)

df.head()

,season,round,session,driver,lap_number,event_time_utc,knowledge_time_utc,ingested_at_utc,source,knowledge_time_rule,...,track_status,position,is_accurate,deleted,deleted_reason,fastf1_generated,speed_i1,speed_i2,speed_fl,speed_st
0,2024,1,R,VER,1,2024-03-02 15:05:19.920000+00:00,2024-03-02 15:05:21.920000+00:00,2026-09-30 07:51:49.820657+00:00,fastf1_archive,lap_complete+2s,...,12,1,False,False,,False,234.0,250.0,276.0,251.0
1,2024,1,R,VER,2,2024-03-02 15:06:56.216000+00:00,2024-03-02 15:06:58.216000+00:00,2026-09-30 07:51:49.820657+00:00,fastf1_archive,lap_complete+2s,...,1,1,True,False,,False,232.0,248.0,276.0,287.0
2,2024,1,R,VER,3,2024-03-02 15:08:32.969000+00:00,2024-03-02 15:08:34.969000+00:00,2026-09-30 07:51:49.820657+00:00,fastf1_archive,lap_complete+2s,...,1,1,True,False,,False,231.0,243.0,276.0,290.0
3,2024,1,R,VER,4,2024-03-02 15:10:09.616000+00:00,2024-03-02 15:10:11.616000+00:00,2026-09-30 07:51:49.820657+00:00,fastf1_archive,lap_complete+2s,...,1,1,True,False,,False,233.0,253.0,276.0,290.0
4,2024,1,R,VER,5,2024-03-02 15:11:46.789000+00:00,2024-03-02 15:11:48.789000+00:00,2026-09-30 07:51:49.820657+00:00,fastf1_archive,lap_complete+2s,...,1,1,True,False,,False,231.0,245.0,276.0,289.0

In [2]:
df.columns

Index(['season', 'round', 'session', 'driver', 'lap_number', 'event_time_utc',
       'knowledge_time_utc', 'ingested_at_utc', 'source',
       'knowledge_time_rule', 'scheduled_laps', 'circuit', 'lap_time_s',
       'sector1_s', 'sector2_s', 'sector3_s', 'lap_start_time_utc',
       'pit_in_time_utc', 'pit_out_time_utc', 'session_time_s',
       'lap_start_session_time_s', 'driver_number', 'team', 'stint',
       'compound', 'tyre_life', 'fresh_tyre', 'track_status', 'position',
       'is_accurate', 'deleted', 'deleted_reason', 'fastf1_generated',
       'speed_i1', 'speed_i2', 'speed_fl', 'speed_st'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1129 entries, 0 to 1128
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   season                    1129 non-null   int32
 1   round                     1129 non-null   int32
 2   session                   1129 non-null   object
 3   driver                    1129 non-null   object
 4   lap_number                1129 non-null   Int32
 5   event_time_utc            1129 non-null   datetime64[us, UTC]
 6   knowledge_time_utc        1129 non-null   datetime64[us, UTC]
 7   ingested_at_utc           1129 non-null   datetime64[us, UTC]
 8   source                    1129 non-null   object
 9   knowledge_time_rule       1129 non-null   object
 10  scheduled_laps            1129 non-null   Int32
 11  circuit                   1129 non-null   object
 12  lap_time_s                1127 non-null   float64
 13  sector1_s                 1108 non-null   float64
 14  sector2_s                 1129 non-null   float64
 15  sector3_s                 1129 non-null   float64
 16  lap_start_time_utc        1129 non-null   datetime64[us, UTC]
 17  pit_in_time_utc           43 non-null     datetime64[us, UTC]
 18  pit_out_time_utc          43 non-null     datetime64[us, UTC]
 19  session_time_s            1129 non-null   float64
 20  lap_start_session_time_s  1129 non-null   float64
 21  driver_number             1129 non-null   object
 22  team                      1129 non-null   object
 23  stint                     1129 non-null   Int32
 24  compound                  1129 non-null   object
 25  tyre_life                 1129 non-null   Int32
 26  fresh_tyre                1129 non-null   boolean
 27  track_status              1129 non-null   object
 28  position                  1129 non-null   Int32
 29  is_accurate               1129 non-null   boolean
 30  deleted                   1129 non-null   boolean
 31  deleted_reason            1129 non-null   object
 32  fastf1_generated          1129 non-null   bool
 33  speed_i1                  1129 non-null   float64
 34  speed_i2                  1129 non-null   float64
 35  speed_fl                  1086 non-null   float64
 36  speed_st                  1129 non-null   float64
dtypes: Int32(5), bool(1), boolean(3), datetime64[us, UTC](6), float64(10), int32(2), object(10)
memory usage: 273.6+ KB

In [4]:
WEATHER_PATH = "../data/raw/weather/season=2024/round=1/session=R/data.parquet"

df_weather = pd.read_parquet(WEATHER_PATH)

df_weather.head()

,season,round,session,sample_index,event_time_utc,knowledge_time_utc,ingested_at_utc,source,knowledge_time_rule,relative_time,air_temp,humidity,pressure,rainfall,track_temp,wind_direction,wind_speed
0,2024,1,R,0,2024-03-02 14:03:56.524000+00:00,2024-03-02 14:03:58.524000+00:00,2026-09-30 07:51:49.838790+00:00,fastf1_archive,observed+2s,0 days 00:00:14.093000,18.9,46.0,1017.1,False,26.5,162,0.9
1,2024,1,R,1,2024-03-02 14:04:56.515000+00:00,2024-03-02 14:04:58.515000+00:00,2026-09-30 07:51:49.838790+00:00,fastf1_archive,observed+2s,0 days 00:01:14.084000,18.9,46.0,1017.0,False,26.5,55,1.0
2,2024,1,R,2,2024-03-02 14:05:56.524000+00:00,2024-03-02 14:05:58.524000+00:00,2026-09-30 07:51:49.838790+00:00,fastf1_archive,observed+2s,0 days 00:02:14.093000,18.9,46.0,1017.0,False,26.5,55,1.0
3,2024,1,R,3,2024-03-02 14:06:56.521000+00:00,2024-03-02 14:06:58.521000+00:00,2026-09-30 07:51:49.838790+00:00,fastf1_archive,observed+2s,0 days 00:03:14.090000,18.9,45.0,1017.0,False,26.2,85,1.1
4,2024,1,R,4,2024-03-02 14:07:56.522000+00:00,2024-03-02 14:07:58.522000+00:00,2026-09-30 07:51:49.838790+00:00,fastf1_archive,observed+2s,0 days 00:04:14.091000,18.9,46.0,1017.0,False,26.2,178,1.0

In [5]:
df_weather.columns

Index(['season', 'round', 'session', 'sample_index', 'event_time_utc',
       'knowledge_time_utc', 'ingested_at_utc', 'source',
       'knowledge_time_rule', 'relative_time', 'air_temp', 'humidity',
       'pressure', 'rainfall', 'track_temp', 'wind_direction', 'wind_speed'],
      dtype='object')

In [6]:
df_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   season               157 non-null    int32
 1   round                157 non-null    int32
 2   session              157 non-null    object
 3   sample_index         157 non-null    int32
 4   event_time_utc       157 non-null    datetime64[us, UTC]
 5   knowledge_time_utc   157 non-null    datetime64[us, UTC]
 6   ingested_at_utc      157 non-null    datetime64[us, UTC]
 7   source               157 non-null    object
 8   knowledge_time_rule  157 non-null    object
 9   relative_time        157 non-null    timedelta64[ns]
 10  air_temp             157 non-null    float64
 11  humidity             157 non-null    float64
 12  pressure             157 non-null    float64
 13  rainfall             157 non-null    bool
 14  track_temp           157 non-null    float64
 15  wind_direction       157 non-null    int32
 16  wind_speed           157 non-null    float64
dtypes: bool(1), datetime64[us, UTC](3), float64(5), int32(4), object(3), timedelta64[ns](1)
memory usage: 17.5+ KB